spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common
---
#debug: false

logging:
  level:
    com.simms.iam: debug
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
    org.springframework.web.servlet: error
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.sql: trace
    org.hibernate.type: trace
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.cache: debug

# SSL적용 시
#server:
#  port: 8080
#  ssl:
#    key-store: classpath:localhost.p12
#    key-store-password: 1234
#    key-store-type: PKCS12
#    enabled: true

spring:
  config:
    import: optional:file:.env[.properties]
    activate:
      on-profile: common
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 50MB

springdoc:
  packages-to-scan: com.alcohol.application
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /api
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

---

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  jwt:
    secret: ${JWT_SECRET}
    token-validity-one-min: 60000

files:
  prefix : d:/upload
  imagePath: /images
  filePath: /others
  viewPath: file:///D://upload//
  logPath: D:/simms/logs


path:
  host: http://localhost:3000
  serial: classpath:skey


server:
  port: 8080

