name: Backend Build & Deploy (release)

on:
  push:
    branches: ["release"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build (Gradle bootJar)
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar
          cp build/libs/*.jar app.jar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app
          path: .

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy JAR to server
        run: |
          APP_DIR="${{ secrets.APP_DIR }}"
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p '$APP_DIR'"
          scp -o StrictHostKeyChecking=no -i key.pem ./app.jar \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:"$APP_DIR/app.jar"

      - name: Restart remotely
        run: |
          APP_DIR="${{ secrets.APP_DIR }}"
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} \
            "bash '$APP_DIR/restart_backend.sh'"
